name: E2E Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  

jobs:
  chrome:

    runs-on: ubuntu-latest
    
    steps:
    - name: Get code
      uses: actions/checkout@v4.2.1

    - name: Setup Node.js 20
      uses: actions/setup-node@v4.0.4
      with:
        node-version: 20

    - name: Setup Python 
      uses: actions/setup-python@v5.2.0
      with:
        python-version: 3.12

    - name: Install Deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Browser Init
      run: rfbrowser init

    - name: Run E2E Tests
      run: robot -d ./results -v BROWSER:chromium tests

    - name: Robot Reporter
      uses: joonvena/robotframework-reporter-action@v2.4
      if: always()
      with:
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}
        report_path: results

    - name: Upload Report
      uses: actions/upload-artifact@v4.4.3
      if: always()
      with:
        name: Chrome test report
        path: results

  firefox:

    runs-on: ubuntu-latest
    
    steps:
    - name: Get code
      uses: actions/checkout@v4.2.1

    - name: Setup Node.js 20
      uses: actions/setup-node@v4.0.4
      with:
        node-version: 20

    - name: Setup Python 
      uses: actions/setup-python@v5.2.0
      with:
        python-version: 3.12

    - name: Install Deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Browser Init
      run: rfbrowser init

    - name: Run E2E Tests
      run: robot -d ./results -v BROWSER:firefox tests

    - name: Robot Reporter
      uses: joonvena/robotframework-reporter-action@v2.4
      if: always()
      with:
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}
        report_path: results

    - name: Upload Report
      uses: actions/upload-artifact@v4.4.3
      if: always()
      with:
        name: Firefox test report
        path: results        